Conference:
    type: entity
    table:  conference
    id:
        id:
          type: integer
          generator:
            strategy: AUTO
    fields:
        name:
          type: string
          length: 50